name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16'

      - name: Install deps
        run: yarn --frozen-lockfile --network-timeout 1000000000

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
